In [1]:
%matplotlib inline
import matplotlib.pyplot as plt, seaborn as sn, mpld3
import pandas as pd, imp, glob, os
from sqlalchemy import create_engine
sn.set_context('notebook')

In [2]:
# Import custom functions
# Connect to db
resa2_basic_path = (r'C:\Data\James_Work\Staff\Heleen_d_W\ICP_Waters\Upload_Template'
                    r'\useful_resa2_code.py')

resa2_basic = imp.load_source('useful_resa2_code', resa2_basic_path)

engine, conn = resa2_basic.connect_to_resa2()

# Import code for trends analysis
resa2_trends_path = (r'C:\Data\James_Work\Staff\Heleen_d_W\ICP_Waters\TOC_Trends_Analysis_2015'
                     r'\Python\icpw\toc_trends_analysis.py')

resa2_trends = imp.load_source('toc_trends_analysis', resa2_trends_path)

In [3]:
# User input
# Specify projects of interest
proj_list = ['ICPW_TOCTRENDS_2015_CA_ATL',
             'ICPW_TOCTRENDS_2015_CA_DO',
             'ICPW_TOCTRENDS_2015_CA_ICPW',
             'ICPW_TOCTRENDS_2015_CA_NF',
             'ICPW_TOCTRENDS_2015_CA_QU',
             'ICPW_TOCTRENDS_2015_CZ',
             'ICPW_TOCTRENDS_2015_Cz2',
             'ICPW_TOCTRENDS_2015_FI',
             'ICPW_TOCTRENDS_2015_NO',
             'ICPW_TOCTRENDS_2015_SE',
             'ICPW_TOCTRENDS_2015_UK',
             'ICPW_TOCTRENDS_2015_US_LTM',
             'ICPWaters Ca']

# Output paths
#plot_fold = r'C:\Data\James_Work\Staff\Heleen_d_W\ICP_Waters\TOC_Trends_Analysis_2015\Trends_Plots'
res_csv = r'C:\Data\James_Work\Staff\Heleen_d_W\ICP_Waters\TOC_Trends_Analysis_2015\res_1990-2012.csv'
dup_csv = r'C:\Data\James_Work\Staff\Heleen_d_W\ICP_Waters\TOC_Trends_Analysis_2015\dup_1990-2012.csv'
nd_csv = r'C:\Data\James_Work\Staff\Heleen_d_W\ICP_Waters\TOC_Trends_Analysis_2015\nd_1990-2012.csv'

In [4]:
# Run analysis 
res_df, dup_df, nd_df = resa2_trends.run_trend_analysis(proj_list, engine,
                                                        st_yr=1990, end_yr=2012,
                                                        plot=False, fold=None)

# Delete mk_std_dev col as not relevant here
del res_df['mk_std_dev']

# Write output
res_df.to_csv(res_csv, index=False)
dup_df.to_csv(dup_csv, index=False)
nd_df.to_csv(nd_csv, index=False)

res_df.head(14).sort_values(by='par_id')

Extracting data from RESA2...
    The database contains duplicate values for some station-date-parameter combinations.
    Only the most recent values will be used, but you should check the repeated values are not errors.
    The duplicated entries are returned in a separate dataframe.

    Some stations have no relevant data in the period specified. Their IDs are returned in a separate dataframe.

    Done.

Converting units and applying sea-salt correction...
    Done.

Calculating statistics...
    Data series for Al at site 101 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 102 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 103 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 104 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 119 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 128 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 147 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 158 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 173 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 185 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 193 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 23456 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 23457 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 23458 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 23460 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for TOC at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for EH at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for ESO4 at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for ECl at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for ENO3 at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for ESO4X at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for ESO4_ECl at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for ECa_EMg at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for ECaX_EMgX at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for ANC at site 23468 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 23545 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 23546 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 36547 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 36560 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for Al at site 36565 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for EH at site 36733 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for EH at site 36739 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for EH at site 36750 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for EH at site 36753 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for EH at site 36793 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for EH at site 36797 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Data series for TOC at site 37835 has fewer than 10 non-null values. Significance estimates may be unreliable.
    Done.

Finished.

,station_id,par_id,period,non_missing,mean,median,std_dev,mk_stat,norm_mk_stat,mk_p_val,trend,sen_slp
10,100,ANC,1990-2012,21,5.322724,4.685420,15.119532,184.0,5.526037,3.275456e-08,increasing,2.078886
0,100,Al,1990-2012,1,276.433655,276.433655,NaN,NaN,NaN,NaN,NaN,NaN
0,101,Al,1990-2012,3,134.411234,133.233703,15.034625,1.0,0.000000,1.000000e+00,no trend,2.395185
9,100,ECaX_EMgX,1990-2012,21,25.464821,24.673333,3.940773,-30.0,-0.875711,3.811873e-01,no trend,-0.107384
8,100,ECa_EMg,1990-2012,21,29.722222,29.333333,4.419444,-40.0,-1.177680,2.389242e-01,no trend,-0.211111
4,100,ECl,1990-2012,21,18.272109,17.142857,3.824173,-107.0,-3.221999,1.272998e-03,decreasing,-0.351074
2,100,EH,1990-2012,21,10.500100,9.772372,3.596191,-119.0,-3.568121,3.595511e-04,decreasing,-0.380255
2,101,EH,1990-2012,23,1.703330,1.318257,1.038155,-161.0,-4.235532,2.280109e-05,decreasing,-0.084711
5,100,ENO3,1990-2012,21,2.180272,2.000000,1.152995,74.0,2.206388,2.735684e-02,increasing,0.078759
3,100,ESO4,1990-2012,21,35.188492,29.166667,15.103219,-173.0,-5.200989,1.982305e-07,decreasing,-2.051373
6,100,ESO4X,1990-2012,21,33.306465,27.400952,14.802535,-175.0,-5.256662,1.466938e-07,decreasing,-1.965706
7,100,ESO4_ECl,1990-2012,21,53.460601,46.309524,18.208253,-165.0,-4.954555,7.249614e-07,decreasing,-2.457341
1,100,TOC,1990-2012,21,6.146667,6.000000,1.184066,111.0,3.326214,8.803429e-04,increasing,0.116569
1,101,TOC,1990-2012,23,3.504348,3.500000,0.649047,133.0,3.499222,4.666181e-04,increasing,0.064706